/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package unbc.ca.distributed.GUI;

import java.util.Iterator;
import java.util.Map;
import javax.swing.DefaultListModel;
import unbc.ca.distributed.graph.elements.Vertex;
import unbc.ca.distributed.management.ObjectFactory;

/**
 *
 * @author behnish
 */
public class UserSelection extends javax.swing.JDialog {

    /**
     * Creates new form UserSelection
     */
    private DefaultListModel listModel;

    public UserSelection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();   
        listModel = new DefaultListModel();
        selectedNodes.setModel(listModel);
        listModel.clear();
        for (Map.Entry<Integer, Vertex> entry : ObjectFactory.getNodes().entrySet()) {
            Vertex vertex = entry.getValue();            
            listModel.addElement("Node "+vertex.getLabel());            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectedNodes = new javax.swing.JList();
        saveSelection = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Select Nodes not this computer");

        selectedNodes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "No Node" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(selectedNodes);

        saveSelection.setText("Save Selection");
        saveSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSelectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(saveSelection)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(saveSelection)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSelectionActionPerformed
        // TODO add your handling code here:
        for (Iterator it = selectedNodes.getSelectedValuesList().iterator(); it.hasNext();) {
            String object = (String) it.next();
            String[] temp = object.split(" ");
            ObjectFactory.getNodes().get(Integer.parseInt(temp[1])).setIsIncludedInNework(false);            
        }
            
        
        dispose();
    }//GEN-LAST:event_saveSelectionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveSelection;
    private javax.swing.JList selectedNodes;
    // End of variables declaration//GEN-END:variables
}
